spring.application.name=StockPricesUpdates
server.port=9696

spring.data.mongodb.uri=mongodb://localhost:27017/stockdb

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.reactor.netty=INFO